// Autogenerated by Thrift Compiler (0.12.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package demo_record

import (
	"bytes"
	"context"
	"reflect"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

type DemoService interface {
  // Parameters:
  //  - Param1
  //  - Param2
  Index(ctx context.Context, param1 string, param2 int64) (r string, err error)
}

type DemoServiceClient struct {
  c thrift.TClient
}

func NewDemoServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *DemoServiceClient {
  return &DemoServiceClient{
    c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
  }
}

func NewDemoServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *DemoServiceClient {
  return &DemoServiceClient{
    c: thrift.NewTStandardClient(iprot, oprot),
  }
}

func NewDemoServiceClient(c thrift.TClient) *DemoServiceClient {
  return &DemoServiceClient{
    c: c,
  }
}

func (p *DemoServiceClient) Client_() thrift.TClient {
  return p.c
}
// Parameters:
//  - Param1
//  - Param2
func (p *DemoServiceClient) Index(ctx context.Context, param1 string, param2 int64) (r string, err error) {
  var _args0 DemoServiceIndexArgs
  _args0.Param1 = param1
  _args0.Param2 = param2
  var _result1 DemoServiceIndexResult
  if err = p.Client_().Call(ctx, "index", &_args0, &_result1); err != nil {
    return
  }
  return _result1.GetSuccess(), nil
}

type DemoServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler DemoService
}

func (p *DemoServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *DemoServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *DemoServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewDemoServiceProcessor(handler DemoService) *DemoServiceProcessor {

  self2 := &DemoServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self2.processorMap["index"] = &demoServiceProcessorIndex{handler:handler}
return self2
}

func (p *DemoServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err := iprot.ReadMessageBegin()
  if err != nil { return false, err }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(ctx, seqId, iprot, oprot)
  }
  iprot.Skip(thrift.STRUCT)
  iprot.ReadMessageEnd()
  x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
  x3.Write(oprot)
  oprot.WriteMessageEnd()
  oprot.Flush(ctx)
  return false, x3

}

type demoServiceProcessorIndex struct {
  handler DemoService
}

func (p *demoServiceProcessorIndex) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := DemoServiceIndexArgs{}
  if err = args.Read(iprot); err != nil {
    iprot.ReadMessageEnd()
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
    oprot.WriteMessageBegin("index", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return false, err
  }

  iprot.ReadMessageEnd()
  result := DemoServiceIndexResult{}
var retval string
  var err2 error
  if retval, err2 = p.handler.Index(ctx, args.Param1, args.Param2); err2 != nil {
    x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing index: " + err2.Error())
    oprot.WriteMessageBegin("index", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return true, err2
  } else {
    result.Success = &retval
}
  if err2 = oprot.WriteMessageBegin("index", thrift.REPLY, seqId); err2 != nil {
    err = err2
  }
  if err2 = result.Write(oprot); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
    err = err2
  }
  if err != nil {
    return
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Param1
//  - Param2
type DemoServiceIndexArgs struct {
  Param1 string `thrift:"param1,1" db:"param1" json:"param1"`
  Param2 int64 `thrift:"param2,2" db:"param2" json:"param2"`
}

func NewDemoServiceIndexArgs() *DemoServiceIndexArgs {
  return &DemoServiceIndexArgs{}
}


func (p *DemoServiceIndexArgs) GetParam1() string {
  return p.Param1
}

func (p *DemoServiceIndexArgs) GetParam2() int64 {
  return p.Param2
}
func (p *DemoServiceIndexArgs) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField1(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.I64 {
        if err := p.ReadField2(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *DemoServiceIndexArgs)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.Param1 = v
}
  return nil
}

func (p *DemoServiceIndexArgs)  ReadField2(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI64(); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Param2 = v
}
  return nil
}

func (p *DemoServiceIndexArgs) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("index_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField2(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *DemoServiceIndexArgs) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("param1", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:param1: ", p), err) }
  if err := oprot.WriteString(string(p.Param1)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.param1 (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:param1: ", p), err) }
  return err
}

func (p *DemoServiceIndexArgs) writeField2(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("param2", thrift.I64, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:param2: ", p), err) }
  if err := oprot.WriteI64(int64(p.Param2)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.param2 (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:param2: ", p), err) }
  return err
}

func (p *DemoServiceIndexArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("DemoServiceIndexArgs(%+v)", *p)
}

// Attributes:
//  - Success
type DemoServiceIndexResult struct {
  Success *string `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewDemoServiceIndexResult() *DemoServiceIndexResult {
  return &DemoServiceIndexResult{}
}

var DemoServiceIndexResult_Success_DEFAULT string
func (p *DemoServiceIndexResult) GetSuccess() string {
  if !p.IsSetSuccess() {
    return DemoServiceIndexResult_Success_DEFAULT
  }
return *p.Success
}
func (p *DemoServiceIndexResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *DemoServiceIndexResult) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField0(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *DemoServiceIndexResult)  ReadField0(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 0: ", err)
} else {
  p.Success = &v
}
  return nil
}

func (p *DemoServiceIndexResult) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("index_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *DemoServiceIndexResult) writeField0(oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin("success", thrift.STRING, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := oprot.WriteString(string(*p.Success)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.success (0) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *DemoServiceIndexResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("DemoServiceIndexResult(%+v)", *p)
}


